### ISSUE TITLE
Untitled NFT hackathon

### ISSUE THREAD

**Issue by pet3r-pan** [Project-Cre8/6elements#2]
Just a small side note, we are also running the Untitled NFT hackathon that is ending on the 27th of Oct (6PM PST)

Feel free to submit your hack to this hackathon as well if you wish :)

https://medium.com/nfthack/untitled-nft-hack-submissions-e1418a3fbfda

**Comment by jcislo** [comment]
Hey pet3r!

Thank you for the invite, but unfortunately we are too late. We are currently ironing out bugs and will let you know when a mainnet launch is scheduled in the near future!
